### ISSUE TITLE
ERR: Can't find any window of the game!

### ISSUE THREAD

**Issue by veiz** [olesgeras/AutoFish#1]
Cannot start fishing, it only shows following error

> [12:20:56] Starting the bot...
> [12:20:56] Can't find any window of the game!

Game locale : **ZH_CN** ， so the game window title is "魔兽世界"

**Comment by olesgeras** [comment]
I assume it's not connected to the game locale but rather to the language of your OS, will test it later on virtual machine. I added the name you gave to the config, I'm not sure what the name of the classes in Chinese OS though... so it might not solve the problem, will check later. 

Thanks for the feedback.

**Comment by olesgeras** [comment]
Added an option for a custom name of the game window.

**Comment by pessimo** [comment]
same error here. where should I look for the right name?

**Comment by olesgeras** [comment]
> same error here. where should I look for the right name?

Have you tried "custom window" option in the advanced settings? Try to tick it off and choose the name of your window.

**Comment by pessimo** [comment]
thanks, "custom window" solves the issue.
