### ISSUE TITLE
Color checking 

### ISSUE THREAD

**Issue by GarBear121** [olesgeras/AutoFish#10]
On servers that don't show the bobber animation 100% of the time can be helped by disabling verticle sync. Suggest an option for looking for a blue color on the bobber, as this part will more often "jerk" when a fish is hooked than seeing the lower red portion.  Can achieve 100% fish rate if color setting is set to max in some spots. Multisampling a higher depth color helps also, along with increasing (faster) checking time of bobber.

**Comment by olesgeras** [comment]
Thanks for the feedback, will test your suggestion and give you results later.
