### ISSUE TITLE
Ui scale and lure

### ISSUE THREAD

**Issue by GarBear121** [olesgeras/AutoFish#11]
My UI scale is set to normal and desktop + wow client are set to 1920x1080. Bot will not click the weapon slot. Using a /script UseAction(); /script PickupInventoryItem(16); /script ReplaceEnchant();
Option to use macro as lure instead of opening character page to apply lure?

**Comment by olesgeras** [comment]
Hey, thanks for the feedback. Yeah it will be a great solution, I'm not very familiar with WoW scripting, will it work for all patches? 

Can you also describe what exactly goes wrong with open character window way: the bot opens the character page but misses the position? Where exactly the mouse moves and which version of wow you are playing?
