### ISSUE TITLE
Game Menu Pop Up

### ISSUE THREAD

**Issue by zanettifilippo** [olesgeras/AutoFish#12]
Hi, I manage to make work the bot but every few seconds it makes the game menu pop up and stop working. Bye game menu I mean the one you get but simply pressing the ESC keyboard button. And of course when the game menu pop up the bot stop working and I have to reset everything again. Do you have any advice?
I m fishing in zereth mortis for Hirukon, I set the graphics to directx11, disable the vertical thing and turned on auto loot.
Please let me know if you have any solutions, it is unusable like this, and I realllllly want to use it!
Thanks

**Comment by olesgeras** [comment]
Thanks for the feedback. Can you record a video how this happens and make a screenshot of the bot settings? Do you have **whitelist** option turned off?
