### ISSUE TITLE
error Can't find any window of the game

### ISSUE THREAD

**Issue by viclee11** [olesgeras/AutoFish#15]
my game info : 
1.WoTLK 
2.Game UI 1.0 is default
3.Game Windows is all screen
4.Enable DX11
but  click start error Can't find any window of the game  pleass help me thanks!

**Comment by viclee11** [comment]
![image](https://user-images.githubusercontent.com/43262983/190153549-9dfcabce-7694-4164-bf45-e708d2473582.png)

**Comment by olesgeras** [comment]
Try to use **Custom window** option and manually choose the window of the game.

**Comment by viclee11** [comment]
> 尝试使用**自定义窗口**选项并手动选择游戏窗口

oh thank you
