### ISSUE TITLE
error Can't set the window to foreground

### ISSUE THREAD

**Issue by viclee11** [olesgeras/AutoFish#16]
my Custom window chose  WoW but  show Can't set the window to foreground Error 
What do I need to do？
thanks!
![image](https://user-images.githubusercontent.com/43262983/190169022-5afe54b4-64eb-4d5c-973f-b1adc2b8c3d0.png)

**Comment by olesgeras** [comment]
What OS are you using?

**Comment by viclee11** [comment]
win11

**Comment by olesgeras** [comment]
Are you using more than 1 window of the game? Because log says it's WIN5 and I wonder. Can you make a screenshot of the custom window list?

**Comment by viclee11** [comment]
yes  using wow window and chrome 
![image](https://user-images.githubusercontent.com/43262983/190182801-c329258f-a200-4aaf-8993-1d5c77cda69a.png)

**Comment by viclee11** [comment]
if is customer windows list show more

![image](https://user-images.githubusercontent.com/43262983/190183367-1fa822d3-b811-4b8f-9350-dca0c4488918.png)

**Comment by olesgeras** [comment]
Did you choose World of Warcraft window in this list before or just check it off? It seems you have chosen wrong window, because the log says it's WIN5 meaning it has found 5 windows with such name.

**Comment by viclee11** [comment]
ok im try thanks!

**Comment by viclee11** [comment]
if Threshold Level is 10 Then do I have to change the place？

**Comment by viclee11** [comment]
im choose wow game windows But there are still mistakes
![image](https://user-images.githubusercontent.com/43262983/190282735-a25f45e9-1b0c-4b58-9b7a-cd005dcdbda5.png)
