### ISSUE TITLE
App is not randomized entirely

### ISSUE THREAD

**Issue by Flax78** [olesgeras/AutoFish#17]
C:\Users\XXXXX\AppData\Roaming\AutoFish is created, instead of the randomized App Name.
Possible detection!

**Comment by Flax78** [comment]
no offend, but i think my statement was and is right. You randomize alot of things! Thats great.
But not everything. 
And since Blizzard not only monitors code injection but also monitors software isntalled on the PC (one ban wave hitting  AutoHotKey users that said thery were using this program not for wow). But OFC you never shure and also Blizzard doesn´t give us insides on their tool (warden). So nobody can post a "proof"on this.
So if its not a bug that this folder exists then forget about the issue i created. 
Its more a feature request then.
thx

**Comment by olesgeras** [comment]
I see, I misunderstood it as "not randomized at all". Will think of making the folder of the cache randomized too, though again I doubt there are any scanning except of current running processes.

**Comment by Flax78** [comment]
> I see, I misunderstood it as "not randomized at all". Will think of making the folder of the cache randomized too, though again I doubt there are any scanning except of current running processes, which are in case of AutoFish pointing to random names of the folder and exe.

the only place i see it is in the Taskmanager under running processes deatails.
that's why I'm thinking
![image](https://user-images.githubusercontent.com/103257572/191103737-5e5e2683-f6c4-4baa-b6bb-2625c4b40589.png)

**Comment by olesgeras** [comment]
Changed the name of the cache folder to simple "Application" in 1.12.0, also removed author and description from package.json.
