### ISSUE TITLE
Whitelist not looting items if there are multiple

### ISSUE THREAD

**Issue by Glutch** [olesgeras/AutoFish#21]
Hello! First off, thank you for the bot, it's wonderful.

However, if you get multiple items in the loot window, it will only loot and consider the first one.
It ALSO seems to struggle heavily with actually looting the correct stuff, right now it's avoiding 90% of loot i actually want.
So i have to use the bot with auto loot right now, which is sad because wotlk has a ton of trash loot
 
Game: WOTLK Classic
UI scale: 1, No addons, Loot window at mouse, auto loot OFF.
Whitelist string "Fangtooth Herring, Bonescale Snapper, Glacial Salmon, Pygmy Suckerfish, Reinforced Crate" (without quotes)

Thank you again!

EDIT: Now it's properly and completely working again. No idea how or why. Changed nothing, oh well, i'm happy!

**Comment by olesgeras** [comment]
UI scale shouldn't be 1, it should be turned off. Also whitelist won't work properly for ultrawide monitors, so you need to use 16:9 windowed mode. There also might be a problem with loot window opening delay, especially if you play on overloaded servers...
