### ISSUE TITLE
Whitelist doesnt work on Retail.

### ISSUE THREAD

**Issue by limonka13** [olesgeras/AutoFish#23]
Hi.

I have issue, when I using whitelist my bot dont catch any withlisted fish, i typed good fish name etc.

**Comment by olesgeras** [comment]
> Turn off Auto Loot, set UI scale to default, turn on Open loot window at mouse.
> Whitelist works properly only with standard 16:9 resolutions (if you use ultrawide monitor, switch to 16:9 windowed mode)

**Comment by limonka13** [comment]
i used it before and all works very well but right now its not working, i have all settings good

**Comment by olesgeras** [comment]
Just tested it, works properly. The issue on your side, try to reinstall the bot and check all the settings again.
