### ISSUE TITLE
Bot clicks to early

### ISSUE THREAD

**Issue by gz2k2** [olesgeras/AutoFish#26]
Is it possible, to add an option, to change the sensitivity of the hook detection?
my Fishbot clicks to early, if i use a bigger bobber

**Comment by olesgeras** [comment]
Try to tweak **Checking delay**, it's also depends on camera position and video settings. Try it from the first person view as well as with different max/min graphics settings.

**Comment by gz2k2** [comment]
thx. i have testet higher delays and now it works better. :)

**Comment by olesgeras** [comment]
Will add some kind of sensitivity in the future updates, so stay tuned.
