### ISSUE TITLE
Fishing in Durotar or TB

### ISSUE THREAD

**Issue by WowStuffs** [olesgeras/AutoFish#3]
It detects red anywhere you try to fish due to the ground being a rust colour. Also, if you can get full Turtle Compatability I will donate you some cash :)

**Comment by olesgeras** [comment]
I will look into making the "red threshold" more universal or will make a separate option for manual configuration of that threshold, you don't need to donate anything for that, thanks for the feedback.

**Comment by olesgeras** [comment]
Added "red threshold" option, you should change it to 50 to make the bot work in Durotar, although the problem with uncomplete bobber animation still an issue.
