### ISSUE TITLE
AutoFish 1.6.2 clicking in the wrong spot

### ISSUE THREAD

**Issue by EricYYang2022** [olesgeras/AutoFish#7]
I'm on Tauri wow for mop 5.4.8.

Everything seems to be working except there is a clear offset between where the bobber actually is and where the application thinks it is. When the bobber moves on recast the mouse moves as well in the right direction, but there is always an offset between the mouse and the bobber that is around the same amount. Any thoughts on how to fix this?

I have attached a reference gif, cropped so that no details about my account are shown:

https://imgur.com/a/NhBGrar (without like a human and with like a human)

I did modify the fishing zone but it also breaks with the default values of x:0.3, y:0.01, w:0.4, h:0.416.

I am on windowed fullscreen 1920x1080.

Please let me know what additional information would be helpful.

**Comment by olesgeras** [comment]
Thanks for the feedback and gifs. Have you tried 1.7.3? Are you using only 1 monitor?

**Comment by EricYYang2022** [comment]
I believe I've tried 1.7.3 as well, and only have 1 monitor. Is there a convenient way to add an offset to mouse.moveTo() that I can basically just adjust myself until the mouse lines up with the fishing bobber's correct location?

Everything else seems to be working perfectly.

**Comment by olesgeras** [comment]
I guess there's no convenient way to fix it right now, you need to clone the repository and add the offset either manually or find the cause of it by checking what values mouse method gets in hookBobber function. I think it might be related to the mouse driver and the bug lies somewhere in the lower domain (in the communication between window and keysender).

**Comment by EricYYang2022** [comment]
I'm not really familiar with javascript but I'm assuming I can just modify in createBot.js the moveTo function indicated in red below by a certain number of pixels and then follow your instructions on using npm to rebuild?

![image](https://user-images.githubusercontent.com/48032682/177184995-d3847cba-fc21-4835-b580-4e8e7dd12102.png)

**Comment by olesgeras** [comment]
Yep, you don't need to rebuild, use **npm start** to launch the app from the CLI. Great that it works! I still wonder what could make such discrepancy between coordinates though. Thanks for your feedback.
