### ISSUE TITLE
Fishing in TBC 

### ISSUE THREAD

**Issue by wergh** [olesgeras/AutoFish#8]
Hello, I have found an issue, in the TBC regions. In the region of Hellfire, Zangar, Terokkar, Nagrand... in the upper central part of the screen, the territories conquered by the alliance (blue) or by the horde (red) appear. The problem is that the software detects that red and therefore aborts the fish when it finds more red than the fish.

Would it be possible to release a new version that would ignore any red above a Y coordinate?

Since fishing never goes that high or shouldn't go that high, I think it would be a good solution to ignore the reds on the top of the screen so that these colors shouldn't interfere.

Thank you very much!

**Comment by olesgeras** [comment]
Hey, thanks for the feedback. You can lower the position of the Fishing Zone in the Advanced Settings, just change Y from 0.01 to e.g. 0.1 to get 10% offset from the top of your game window.

**Comment by olesgeras** [comment]
Added visual configuration for Fishing Zone.
